# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Internetdata < Formula
  desc "Official CLI for the InternetData API"
  homepage "https://internetdata.io"
  version "1.1.1"
  license "MIT"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/internetdata/cli/releases/download/v1.1.1/internetdata_1.1.1_darwin_arm64.tar.gz"
      sha256 "ca2489795699cdf0a5c5cb0652d97c750ac6542c1700045293df0ea117852eb9"
    end
    on_intel do
      url "https://github.com/internetdata/cli/releases/download/v1.1.1/internetdata_1.1.1_darwin_amd64.tar.gz"
      sha256 "5e59ddea552eae3802bfad28b6a1c4e184dce712d379b681feca155658e5ef8f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/internetdata/cli/releases/download/v1.1.1/internetdata_1.1.1_linux_arm64.tar.gz"
      sha256 "8357a70efe01c2e8994462442541c42573dbaaf982d4d7c593e54b3b9a85518e"
    end
    on_intel do
      url "https://github.com/internetdata/cli/releases/download/v1.1.1/internetdata_1.1.1_linux_amd64.tar.gz"
      sha256 "2e879cdd35aa0db7a89afbb061d8e9b51c0f2f66a37cbe5dfcf4ce29b2b53f4f"
    end
  end

  def install
    bin.install "internetdata"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/internetdata version")
  end
end
