# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Internetdata < Formula
  desc "Official CLI for the InternetData API"
  homepage "https://internetdata.io"
  version "1.1.0"
  license "MIT"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/internetdata/cli/releases/download/v1.1.0/internetdata_1.1.0_darwin_arm64.tar.gz"
      sha256 "421f6d7403d381863e1a85d189d9c3c17c5fe58fbaf963be2175df857b88f019"
    end
    on_intel do
      url "https://github.com/internetdata/cli/releases/download/v1.1.0/internetdata_1.1.0_darwin_amd64.tar.gz"
      sha256 "7a44362ffda3608c79cfdda5e8b65eff4b8e1e5cbebb2ed6fbfaa886349d78fe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/internetdata/cli/releases/download/v1.1.0/internetdata_1.1.0_linux_arm64.tar.gz"
      sha256 "612d7f601705c1982c433a49f1af73aff03dba8f1ac5a61e442efe61739c3967"
    end
    on_intel do
      url "https://github.com/internetdata/cli/releases/download/v1.1.0/internetdata_1.1.0_linux_amd64.tar.gz"
      sha256 "0a37d16d7d40283ab5f770feb4418321f86d9ab668d32ed1ad8d98d3523213e9"
    end
  end

  def install
    bin.install "internetdata"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/internetdata version")
  end
end
