# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Internetdata < Formula
  desc "Official CLI for the InternetData API"
  homepage "https://internetdata.io"
  version "1.2.0"
  license "MIT"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/internetdata/cli/releases/download/v1.2.0/internetdata_1.2.0_darwin_arm64.tar.gz"
      sha256 "a3ee0829e6a17637319b7aa1d48703b4192eac2038b3097898872a3a701ba118"
    end
    on_intel do
      url "https://github.com/internetdata/cli/releases/download/v1.2.0/internetdata_1.2.0_darwin_amd64.tar.gz"
      sha256 "76e343e40d724e103e1a4fab6d4246e6e5a7209bfded0a1405ce337a4d2fb3dd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/internetdata/cli/releases/download/v1.2.0/internetdata_1.2.0_linux_arm64.tar.gz"
      sha256 "89ee54a2eb58369aee10d85ea9ef13b9ccb8f1c025f4885134dd8932fc3901d6"
    end
    on_intel do
      url "https://github.com/internetdata/cli/releases/download/v1.2.0/internetdata_1.2.0_linux_amd64.tar.gz"
      sha256 "c753dcf8ff22d31bbeea9901521495ac7f066f79e52803dd316a1514cabd9e23"
    end
  end

  def install
    bin.install "internetdata"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/internetdata version")
  end
end
