# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Mmdb < Formula
  desc "Read, import, export, diff and verify MMDB files"
  homepage "https://github.com/internetdata/mmdb"
  version "1.0.0"
  license "GPL-3.0-only"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/internetdata/mmdb/releases/download/v1.0.0/mmdb_1.0.0_darwin_arm64.tar.gz"
      sha256 "3ddfe9bb5f55b93fe48ad6b857fb30b57fcd73b7473985f47316d28ae663e456"
    end
    on_intel do
      url "https://github.com/internetdata/mmdb/releases/download/v1.0.0/mmdb_1.0.0_darwin_amd64.tar.gz"
      sha256 "3dd99fac4edd383e85b2441ab993e1bf7fa3d45bfb7d296cf060c80394c8eaf9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/internetdata/mmdb/releases/download/v1.0.0/mmdb_1.0.0_linux_arm64.tar.gz"
      sha256 "ed4af465d9851451e140b421a12717dfc81e4de2c9df5722bc75c16a20dd032e"
    end
    on_intel do
      url "https://github.com/internetdata/mmdb/releases/download/v1.0.0/mmdb_1.0.0_linux_amd64.tar.gz"
      sha256 "26814cac4b058e19d1d26329207005e339982706320fa53fe28c028a8205512f"
    end
  end

  def install
    bin.install "mmdb"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mmdb version")
  end
end
