# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Mmdb < Formula
  desc "Read, import, export, diff and verify MMDB files"
  homepage "https://github.com/internetdata/mmdb"
  version "1.2.1"
  license "GPL-3.0-only"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/internetdata/mmdb/releases/download/v1.2.1/mmdb_1.2.1_darwin_arm64.tar.gz"
      sha256 "c3d51b45bfdd7e8ca1d406eecdb0f793e52185ca0348b13eef802f84d8f67c70"
    end
    on_intel do
      url "https://github.com/internetdata/mmdb/releases/download/v1.2.1/mmdb_1.2.1_darwin_amd64.tar.gz"
      sha256 "1dcda5c4af1604ab1d264be53bb696723f33885bf820f37d5f7a947fee515e23"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/internetdata/mmdb/releases/download/v1.2.1/mmdb_1.2.1_linux_arm64.tar.gz"
      sha256 "d1d4aa2e7b8c031af4719850fbc912cd265f395e06885c9fdbea2c88a2497ce9"
    end
    on_intel do
      url "https://github.com/internetdata/mmdb/releases/download/v1.2.1/mmdb_1.2.1_linux_amd64.tar.gz"
      sha256 "f25142761101ae3fb98123c70db1bb4202cacce7c3f6d6d4eac3846842f95340"
    end
  end

  def install
    bin.install "mmdb"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mmdb version")
  end
end
