# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Mmdb < Formula
  desc "Read, import, export, diff and verify MMDB files"
  homepage "https://github.com/internetdata/mmdb"
  version "1.1.0"
  license "GPL-3.0-only"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/internetdata/mmdb/releases/download/v1.1.0/mmdb_1.1.0_darwin_arm64.tar.gz"
      sha256 "c8d54cd4afc06d81fbcfba4b02c65d62db24c604546b5b20d41276beae7223ed"
    end
    on_intel do
      url "https://github.com/internetdata/mmdb/releases/download/v1.1.0/mmdb_1.1.0_darwin_amd64.tar.gz"
      sha256 "98eab4353433e10ceba11130af43f11421d984877c5606dd135357e898a90e75"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/internetdata/mmdb/releases/download/v1.1.0/mmdb_1.1.0_linux_arm64.tar.gz"
      sha256 "2ad6115b1b0cc93d7fbfc5cf9121724dbed9000af92f0af9ca2fa9dc3e352ee6"
    end
    on_intel do
      url "https://github.com/internetdata/mmdb/releases/download/v1.1.0/mmdb_1.1.0_linux_amd64.tar.gz"
      sha256 "0cd25db103389e9a61eba1a84efb6845b7125d9a63926f0d8beb6fef742c7880"
    end
  end

  def install
    bin.install "mmdb"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mmdb version")
  end
end
